{% set name = "sense2vec" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/explosion/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: c835dbe555b88298477b7216b78127c35f80476c127f0999647756dc69dc47e2

build:
  number: 0
  skip: true  # [win and vc<14]
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - cython
    - python
  run:
    - numpy >=1.15.0
    - python
    - srsly >=2.4.0,<3.0.0
    - spacy >=3.0.0, <4.0.0
    - wasabi >=0.8.1, <1.1.0
    - catalogue >=2.0.1, <2.1.0
    - importlib_metadata >=0.20
test:
  imports:
    - sense2vec
    - sense2vec.tests

about:
  home: https://github.com/explosion/sense2vec
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: word2vec with NLP-specific tokens
  dev_url: https://github.com/explosion/sense2vec

extra:
  recipe-maintainers:
    - mxr-conda
    - benhuff
    - adbeda
    - tata17
    - rluria14
    - oblute
    - JennaLipscomb
