{% set name = "sense2vec" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/explosion/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 086e848eb6334dfd399fbf8326df723e55934b92e08d83c32f9b188981c0392f

build:
  number: 0
  skip: True  # [win and vc<14]
  script: "{{ PYTHON }} -m pip install . -vv "

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - cymem >=2.0.2,<2.1.0
    - murmurhash >=0.28.0,<1.1.0
    - pip
    - cython
    - preshed >=2.0.1,<2.1.0
    - python
  run:
    - cymem >=2.0.2,<2.1.0
    - murmurhash >=0.28.0,<1.1.0
    - numpy >=1.15.0
    - preshed >=2.0.1,<2.1.0
    - python
    - srsly >=0.1.0,<1.1.0

test:
  imports:
    - sense2vec
    - sense2vec.tests

about:
  home: https://github.com/explosion/sense2vec
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'word2vec with NLP-specific tokens'
  dev_url: https://github.com/explosion/sense2vec

extra:
  recipe-maintainers:
    - benhuff
    - adbeda
    - tata17
